### ISSUE TITLE
Only 8 pixels high available

### ISSUE THREAD

**Issue by alex7088** [robert-hh/SH1106#1]
With Framebuffer1 I can use only 8 pixels high dipslay. When I changes from Framebuffer1 to Framebuffer problem solved

**Comment by robert-hh** [comment]
Hello Alex. Thanks for the note. It is not clear to me what you mean with: 
> 8 pixels high dipslay

Do you mean monochrome displays or really a display with the geometry width x 8? I used the driver with a monochrome 128x64 pixel display. What kind of display are you using?
Besides that, I think the change you used is safe.

**Comment by alex7088** [comment]
No this is common 128x64 but with original driver it shown only 128x8
Other part of display was off
I l send a photo


14 апр 2017 г. 11:21 PM пользователь "robert-hh" <notifications@github.com>
написал:

**Comment by robert-hh** [comment]
Found the reason: The underlying class was changed, and the format parameter obsolete for Framebuffer1 was taken stride value. Anyhow, I updated the repository.
Thanks a lot.
