### ISSUE TITLE
Change Text size

### ISSUE THREAD

**Issue by aBugMansLife** [robert-hh/SH1106#14]
I might be missing it, but i can't seem to find a command to change the text size on the SH1106 display.
Is it possible to increase and decrease text size with this library?

**Comment by robert-hh** [comment]
No, it is not possible. It is based on the framebuffer class which supports only one font & size. But if you look into the Forum or in the Repositories of @pythoncoder, you will find a very flexible method of using any font and size you like. Sample links:
https://github.com/peterhinch
https://github.com/peterhinch/micropython-font-to-py
https://github.com/peterhinch/micropython-epaper
