### ISSUE TITLE
Is this compatible with a Micro:Bit V2?

### ISSUE THREAD

**Issue by bsmntoid** [robert-hh/SH1106#19]
I don't want to sound stupid, but if I add this driver to a Micro:Bit V2, will it function correctly? I just want to be sure it'll work before I waste a good $20 on a display.

**Comment by robert-hh** [comment]
The driver itself is simple and requires little resources besides the frame buffer. If you just need I2C, you can remove the SPI part, and vice versa. But the driver uses the framebuffer module, and that if acquires 1k RAM for the buffer. At  a V2 model this should not be a problem.
