### ISSUE TITLE
blit: 'FrameBuffer' object has no attribute 'height'

### ISSUE THREAD

**Issue by max-m-s** [robert-hh/SH1106#23]
The blit function seems to be looking for height property in the passed FrameBuffer which is not visible (any more?).

**Comment by CRImier** [comment]
hmm weird! I don't exactly have hardware to test with atm, but I will look to it when I get a chance!

**Comment by max-m-s** [comment]
I'm on a RPi Pico with MicroPython "rp2-pico-20220618-v1.19.1.uf2", if that matters.

**Comment by shaneapowell** [comment]
I also ran into the same error with micropython on my esp8266.
The fix for me was simply to alter line 200 in `sh1106.py` from 
`self.register_updates(y, y+fbuf.height)`
to
`self.register_updates(y, y+self.height)`

**Comment by robert-hh** [comment]
The code was changed accordingly in commit 3ccafeb7bbe99112c448d98d98a9724eb65784c4.
