### ISSUE TITLE
.blit with negative y offset fails

### ISSUE THREAD

**Issue by pdg137** [robert-hh/SH1106#32]
If you blit an image on the sh1106 framebuf with negative offset, this line makes it attempt to register changes off the screen, which fails with an error:

https://github.com/robert-hh/SH1106/blob/9b75517e8004210e2497132b5778bb386de0853b/sh1106.py#L225

I think changing it to `start_page = max(0, y0 // 8)` solves the problem.

**Comment by CRImier** [comment]
yeah that ought to do it!

**Comment by pdg137** [comment]
Actually, I think you need it on the next line too!

**Comment by robert-hh** [comment]
Please make a PR for the change.

**Comment by pdg137** [comment]
Okay, there it is!
